### PR TITLE
#420 Disable direct messages for more than 10 people and improve user…

### PR DESCRIPTION
**Pull request by stephanevieira75**
https://user-images.githubusercontent.com/36481167/127638975-5f3ae602-351d-46f1-9105-08455328e049.mp4

Capture d’écran de 2021-07-30 14-42-51
Capture d’écran de 2021-07-30 14-42-23

### CODE REVIEW

**Comment by RomaricMourgues** [comment]
I propose to change the text to “Créer une chaîne privée”
(Instead of the long text with the link inside)

**Comment by RomaricMourgues** [comment]
Also do not have the “pointer” cursor on the blue background text. And include a line break to see the full text in multiple lines.

**Comment by RomaricMourgues** [comment]
We can put back the "à la place" / "instead".

**Comment by stephanevieira75** [comment]
> We can put back the "à la place" / "instead".

Done
Capture d’écran de 2021-07-30 19-49-19

**Review by RomaricMourgues — APPROVED** [review]

**Pull request merged**
