### PR TITLE
🛠 Multiple fixes guest invitation, moderation, and more

### PR DESCRIPTION
**Pull request by RomaricMourgues**
- [x] add better logs for previews
- [x] change guest invitation api on console
- [x] #1856
- [x] #1562 
- [x] Change default mention to "all"
- [x] Fix code to work with Fastify new version
- [x] #1916 
- [x] #214 
- [x] https://github.com/linagora/Twake/issues/1666
- [x] https://github.com/linagora/Twake/issues/1937

### CODE REVIEW

**Comment by RomaricMourgues** [comment]
@BenoitTallandier this update means that we'll always miss the inviter. name in the invitation emails. But anyone will be able to invite (members AND admins of the company)
Do you confirm ?

**Comment by RomaricMourgues** [comment]
The email subject will be “has invited you to SuperCompany” instead of “Romaric has invited you to SuperCompany”

**Comment by BenoitTallandier** [comment]
Ok, so I confirm that is what we want to do ;-)

**Comment by BenoitTallandier** [comment]
@RomaricMourgues Ok, let's do as you proposed 👍

**Pull request merged**
