### PR TITLE
CLI for console merge

### PR DESCRIPTION
**Pull request by chamerling**
Missing parts:

- [x] Create the Twake console HTTP client and integrate it in the command
- [x] Test with real console

### CODE REVIEW

**Comment by RomaricMourgues** [comment]
@chamerling we didn't talk about how to do the link between Twake users and Console users, the table for this is "external_user_repository" and for companies "external_group_repository", it contains the console id and the Twake id.

**Comment by chamerling** [comment]
@RomaricMourgues OK so for the external_* entities, there is a `service_id: string` to fill for both. I will set the value configurable from the CLI, anyway, what is the value we are currently using for the console `twake_console`?

**Comment by RomaricMourgues** [comment]
It is "console" :)

**Review by RomaricMourgues — APPROVED** [review]
I read some part of it, it seems good to me good work

**Review by RomaricMourgues — APPROVED** [review]

**Pull request merged**
