### PR TITLE
🌟 Applications node part 1

### PR DESCRIPTION
**Pull request by romanesko**
it's a draft

### CODE REVIEW

**Comment by RomaricMourgues** [comment]
@romanesko ping me when it's ready to merge for step 2, we'll create a new PR for step 3 and later

**Comment by romanesko** [comment]
It's ready
But I need to notice
1. now responses of /api/* endpoints doesn't return `resource` (regarding the docs), it's could be a mistake and we need to wrap it.
2. the privateKey returns only once right after the application creating (not after get or edit)

**Comment by RomaricMourgues** [comment]
For the 1. ok we'll need to fix it later still
For the 2. are we talking about the app secret ? Why is it visible only once ?

**Comment by romanesko** [comment]
1. I can fix it now, that's quick
2. we have this data available to any admin of the company, it does not look very right, but I can open the data for all of them

**Comment by RomaricMourgues** [comment]
Yes for now it will be visible to all admin in the company I confirm (but good point I will keep it in mind)

**Comment by RomaricMourgues** [comment]
@romanesko ping me by sms or Twake when my last comment is implemented so I can merge :)

**Pull request merged**
