### PR TITLE
🌟 message delivery status (#2451)

### PR DESCRIPTION
**Pull request by rezk2ll**
## Description

- adds message delivery status
- adds an endpoint to mark messages as delivered
- adds an endpoint to mark messages as seen 

## Related Issue

#2451 

## Motivation and Context

- adds the ability to know if messages have been delivered, read

## How Has This Been Tested?

- locally

### being sent
image

### sent message
image

### failed message
image

### delivered message
image

### seen message
image

https://user-images.githubusercontent.com/6764881/185974730-92c1622f-f78e-4a63-9716-1eb465233d63.mp4

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by RomaricMourgues** [comment]
Hi, that's impressive in the video ! I see that the icon goes from sent to delivered, then again to sent then to delivered again, why is happening here ?

**Comment by RomaricMourgues** [comment]
Also could you update the documentation here: https://www.notion.so/linagora/API-Rest-Websockets-1f3f54f110b44743a102baf269f66ebd for the notification aknowledgement and create an issue for the mobile team to implement a call to this endpoint in background process when receiving a push notification ?

Then there is some documentation about marking messages as read here https://www.notion.so/linagora/Rest-APIs-Views-bookmarks-search-b022d821bb2a44babec096103c0fda2c. Same, mobile team should be informed via a new ticket.

And finally two points to be discussed:
- how does it behave inside threads
- what about the modal with the list of who read a specific message

**Comment by rezk2ll** [comment]
> Hi, that's impressive in the video ! I see that the icon goes from sent to delivered, then again to sent then to delivered again, why is happening here ?

it was an issue with message propagation and WebSocket updates, fixed in https://github.com/linagora/Twake/pull/2452/commits/a97a9bdfed387435a2c4ca72f8782991b7232d06

**Comment by rezk2ll** [comment]
> 



> Also could you update the documentation here: https://www.notion.so/linagora/API-Rest-Websockets-1f3f54f110b44743a102baf269f66ebd for the notification aknowledgement and create an issue for the mobile team to implement a call to this endpoint in background process when receiving a push notification ?
> 
> Then there is some documentation about marking messages as read here https://www.notion.so/linagora/Rest-APIs-Views-bookmarks-search-b022d821bb2a44babec096103c0fda2c. Same, mobile team should be informed via a new ticket.
> 
> And finally two points to be discussed:
> 
> * how does it behave inside threads
> * what about the modal with the list of who read a specific message

threads and the message display are gone when we introduced the quote reply feature.

**Comment by RomaricMourgues** [comment]
> > 
> 
> > Also could you update the documentation here: https://www.notion.so/linagora/API-Rest-Websockets-1f3f54f110b44743a102baf269f66ebd for the notification aknowledgement and create an issue for the mobile team to implement a call to this endpoint in background process when receiving a push notification ?
> > Then there is some documentation about marking messages as read here https://www.notion.so/linagora/Rest-APIs-Views-bookmarks-search-b022d821bb2a44babec096103c0fda2c. Same, mobile team should be informed via a new ticket.
> > And finally two points to be discussed:
> > 
> > * how does it behave inside threads
> > * what about the modal with the list of who read a specific message
> 
> threads and the message display are gone when we introduced the quote reply feature.

Threads are still here in the non direct channel views no ?

And I was talking about this modal, with the UserReadCursors we should be able to compute this view what do you think? 
Screenshot 2022-08-29 at 15 31 42

**Pull request merged**
