### PR TITLE
📁 #2652 added download drive item as a zip archive

### PR DESCRIPTION
**Pull request by rezk2ll**
related to #2652

### CODE REVIEW

**Review by RomaricMourgues — COMMENTED** [review]
It seems to be exactly what I had in mind 👍 
- Could you check what happen in client closes the connection during the zip generation ?
- Also what happens for files that cannot be downloaded (links, external files etc), we should ignore them for now

**Review by RomaricMourgues — APPROVED** [review]

**Comment by RomaricMourgues** [comment]
All good to me

**Comment by rezk2ll** [comment]
> I'll merge when you want me to merge

you can merge it.

**Comment by RomaricMourgues** [comment]
Forgot about it, thanks

**Pull request merged**
