### PR TITLE
📱 Fix web mobile view 

### PR DESCRIPTION
**Pull request by BenoitTallandier**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added the Signed-off-by statement at the end of my commit message.

### CODE REVIEW

**Comment by RomaricMourgues** [comment]
@BenoitTallandier is it ready to merge?

**Comment by BenoitTallandier** [comment]
Not yet, I'm on an other bug and after you can merge :)

**Comment by RomaricMourgues** [comment]
Ok I put it in draft in the meanwhile then

**Comment by RomaricMourgues** [comment]
Oh right the [WIP] prefix is great too :)

**Comment by BenoitTallandier** [comment]
@RomaricMourgues It can be merged :)

**Pull request merged**
