### PR TITLE
👨‍💻 Create Commit & Pull Request Title Format

### PR DESCRIPTION
**Pull request by shivam9593**

### CODE REVIEW

**Comment by RomaricMourgues** [comment]
Can you clean the PR before to merge it ?

**Comment by shivam9593** [comment]
> Can you clean the PR before to merge it ?

I have selected the option to squash the commits once it will be merged. I am not using Git Desktop and using the browser version so I cannot squash the commits unless it is merged.

**Comment by RomaricMourgues** [comment]
I did it for you, the commands are:
`git checkout shivam9593-patch-5; git reset HEAD~4; git pull upstream main; git cherry-pick c2aa55d7834c89ac4027e37698d7d53130836aff; git push upstream HEAD:shivam9593-patch-5 --force`

**Review by RomaricMourgues — APPROVED** [review]
If it is good for you, it's good for me

**Pull request merged**
