### PR TITLE
Refactored Dockerfiles to reduce excessive RUNs

### PR DESCRIPTION
**Pull request by tk-nguyen**
This will make docker builds use less layers for building images. 

Build time will also be increased (due to caching for fewer layers).

I also refactored nginx image to use multi-stage build and restructured the build steps for other images.

Please test to see if these changes are not breaking anything. It should not be, but there might be some small problems 😅

### CODE REVIEW

**Comment by ducnm0711** [comment]
nice change,

**Comment by tk-nguyen** [comment]
This PR should be ready now 👍

**Review by RomaricMourgues — APPROVED** [review]

**Comment by RomaricMourgues** [comment]
Could you rebase it to the "develop" branch first ? All PR must be opened on the "develop" branch first and then when merged they will be added to all the environments up to main.

**Review by RomaricMourgues — CHANGES_REQUESTED** [review]
Rebase on branch "develop"

**Comment by tk-nguyen** [comment]
Sure. Should I open a new PR then?

**Pull request closed without merging**
